### ISSUE TITLE
Action with failed step still showing as success

### ISSUE THREAD

**Issue by Shaun-Harrison** [toko-bifrost/ms-teams-deploy-card#13]
Hello

I guess there may be two issues here

Firstly, I noticed that my action has failed on a previous step, because of this the Teams message step wasn't ran at all, to say if it had succeeded or failed, so I added `if: always()` to the step. This then got the teams message to post regardless of previous steps failing, but the result in the teams message still said success although a step failed

![image](https://user-images.githubusercontent.com/46562010/84666462-028c1700-af19-11ea-9287-05d45e683a3a.png)

**Comment by AdamHansrod** [comment]
I think this is the same issue I had that led me to suggest the ['show-on-failure' feature](https://github.com/toko-bifrost/ms-teams-deploy-card/issues/10)

**Comment by aldwyn-acn** [comment]
Hi @Shaun-Harrison. Version [3.1.0](https://github.com/toko-bifrost/ms-teams-deploy-card/releases/tag/3.1.0) have been released and kindly refer to the `Known Issues` in the docs. Thank you.
