### ISSUE TITLE
Add ability to include base64 images

### ISSUE THREAD

**Issue by hammadj** [toko-bifrost/ms-teams-deploy-card#19]
In our workflow we generate a QR code that links to a live app preview. Would be great if we could use the sections.images field to add the base64 data for the QR code directly on the file: https://stackoverflow.com/a/57034497

**Comment by aldwyn-acn** [comment]
Hi @hammadj, that is a nice feature to add. Unfortunately, the activity card misplaces the expected image on the bottom part. But you are welcome to send a pull request and let me know how you want it to be displayed on the activity card. I'm closing this for now. Thank you.
