### ISSUE TITLE
Commit message uses hashes only on pull-request trigger

### ISSUE THREAD

**Issue by ghost** [toko-bifrost/ms-teams-deploy-card#26]
Hi, 

when using pull-request trigger, instead of text commit message, I'm keep getting:

`Merge ff547055cd65c6b061f8815c594c001324025bf9 into 67d0559eb0f5965d1a73842abe620969cf0bf401`

Which is obviously not informative. Is there way to fix it?
On push event it works well.

Regards, Akhan

**Comment by aldwyn-acn** [comment]
Hi @akhanqi. I think it makes sense. In your case, you are making `ff547055cd65c6b061f8815c594c001324025bf9` a head commit of `67d0559eb0f5965d1a73842abe620969cf0bf401`, and is a `pull-request` type, not a `push` type. Hence, in a PR, there are two existent commits wherein Github API would not be deciding which message from the two commits it will take. If that's what the Github API gives off on the PR's `commit.message`, which really is, then let it be. If you really need to get comprehensive commit messages with ms-teams-deploy-card, resort to making your Github Actions workflows receive only `on: [push]` triggers.
