### ISSUE TITLE
Status never change

### ISSUE THREAD

**Issue by MinPhoneWaveMoney** [toko-bifrost/ms-teams-deploy-card#28]
<img width="907" alt="Screen Shot 2020-08-18 at 15 11 58" src="https://user-images.githubusercontent.com/58675243/90491367-d7ff4a00-e165-11ea-9520-1a97b2cc84f3.png">
<img width="566" alt="Screen Shot 2020-08-18 at 15 17 12" src="https://user-images.githubusercontent.com/58675243/90491583-1e54a900-e166-11ea-8e12-1037682a88f2.png">

The above code is what I using in current my project. What I am wronging?
Thanks

**Comment by aldwyn-acn** [comment]
Hi @MinPhoneWaveMoney, you must have named your job. Kindly check [Known Issues](https://github.com/toko-bifrost/ms-teams-deploy-card#known-issues), item 5. It's also discussed in #22 .

**Comment by MinPhoneWaveMoney** [comment]
Thanks
