### ISSUE TITLE
Show cards logic issue

### ISSUE THREAD

**Issue by uncledru** [toko-bifrost/ms-teams-deploy-card#29]
Setting both `show-on-exit` and `show-on-failure` sets the configuration to not show card upon job exit. See images below. 

![image](https://user-images.githubusercontent.com/7441475/90703985-3e1ac880-e25d-11ea-8094-a50ba032d372.png)

![image](https://user-images.githubusercontent.com/7441475/90703952-26434480-e25d-11ea-9215-22a1dfcb6c2e.png)

The issue seems to lie somewhere [here](https://github.com/toko-bifrost/ms-teams-deploy-card/blob/master/src/post.ts#L12)

I can contribute if needed :)

**Comment by aldwyn-acn** [comment]
Hi @uncledru, I've made clear in the README the following descriptions 😁 

| `show-on-exit`      | `false`  | `true`     | Show an MS Teams card upon **_exiting_** this Github Actions job, regardless if it's a successful or a failed exit                                                                                                                                                         |
| `show-on-failure`   | `false`  | `false`    | Show an MS Teams card upon **_exiting_** this Github Actions job and status is `FAILURE`; **This will override any boolean value of `show-on-exit`**, e.g. with `show-on-exit=false` and `show-on-failure=true`, the notification card will still proceed upon job failure |

**Comment by uncledru** [comment]
Got it. Thanks @aldwyn-acn! If I'm understanding correctly -- I need to set 
`show-on-exit` to `false` and 
`show-on-failure` to `true

to get both failure and success notifications on exit?

**Comment by aldwyn-acn** [comment]
@uncledru to get both failure and success notifications on exit, you only have to set `show-on-exit` to `true`. Or don't set any value on it at all because its default is already `true`. Don't mind setting the `show-on-failure`.

**Comment by uncledru** [comment]
Awesome. Thank you! Loving the action :)
