### ISSUE TITLE
Action doesn't output action status

### ISSUE THREAD

**Issue by Kampe** [toko-bifrost/ms-teams-deploy-card#3]
After getting the action working in teams, I noticed the action doesn't include the status of the action it's part of, which would be super useful I'd imagine to most people!

Ideally statuses such as SUCCESS, FAILED, CANCELLED would be present on the action card in some way.

**Comment by aldwyn-acn** [comment]
Hi @Kampe,

I appreciate your idea on this one. I actually researched this on how to do it via MS Teams webhook. It would be ideally nice to see an appended comment on a deployment card in the channel about the build status, but there is no way a webhook can tell which message a comment should be appended to. And on your idea about putting a manual status on the action, I'm assuming this action would be called again somewhere at the end of the build. I think this would be a waste of space on the Teams channel esp. when there are simultaneous commits pushed. Let me know what's your opinion on this.

Thank you.

**Comment by Kampe** [comment]
Usually I only call the webhook once the action is complete, not multiple times a run, atleast that's how I manage all my pipelines for chat ops.

**Comment by aldwyn-acn** [comment]
Hi @Kampe,

It would be ideal to show the notification at the start (e.g. upon after checking out the code via `actions/checkout@v2`) and then show the result at the end of the build as well (e.g. a one-liner statement with a commit identified and with either `STABLE`, `UNSTABLE`, or `FAILED`). I'm thinking we can do just like how `actions/checkout` is done. It wraps around the entire build process.

<img width="496" alt="Screen Shot 2020-03-13 at 11 46 58 PM" src="https://user-images.githubusercontent.com/32511827/76637074-13796500-6585-11ea-9baf-84c7cbb07ef0.png">

**Comment by Kampe** [comment]
Absolutely, I think that'd be a great addition - may not be so relevant to include all the files that changed with the success/fail call, maybe make it optional?

**Comment by aldwyn-acn** [comment]
@Kampe, we have to wait for the wrapper feature to be fully documented though. It is tracked internally as per here: https://github.community/t5/GitHub-Actions/post-and-post-if-metadata-tags-are-not-documented/td-p/40652

**Comment by aldwyn-acn** [comment]
@Kampe this has been implemented on ([v3.0.0](https://github.com/toko-bifrost/ms-teams-deploy-card/releases/tag/3.0.0)).
