### ISSUE TITLE
Bug: Unhandled Error Exception

### ISSUE THREAD

**Issue by RaghulXander** [toko-bifrost/ms-teams-deploy-card#32]
Hi,
- I was trying to use your ms-teams-card and have added required details in yml but i get this is Exception as below

![Screenshot 2020-10-21 at 12 03 05 PM](https://user-images.githubusercontent.com/32994803/96681926-a5f0ab00-1395-11eb-8183-cc16dfb560cb.png)

**Comment by aldwyn-acn** [comment]
Hi @RaghulXander,

Could you please paste here your workflow yaml config? Thanks.

**Comment by aldwyn-acn** [comment]
Hi @RaghulXander, I'm closing this for now. Just reopen it when you managed to accommodate my request. Thank you.
