### ISSUE TITLE
deploy-title not working as expected..

### ISSUE THREAD

**Issue by nreddipalle** [toko-bifrost/ms-teams-deploy-card#7]
@aldwyn-acn I would like to display the PR URI as part of the card..
Implemented this: 
` name: Notify dedicated teams channel
        uses: toko-bifrost/ms-teams-deploy-card@2.1.2
        if: ${{ steps.mapvalues.outputs.requestedteams }}
        with:
          github-token: ${{ secrets.TOKEN }}
          webhook-uri: ${{ steps.pr_notification.outputs.MS_TEAMS_WEBHOOK_URI }}
          timezone: "America/Toronto"
          deploy-title: "'$eventuser' requested review on a Pull Request:
                          $pruri"`
But the PR URI is not showing up as part of card within Microsoft teams..

**Comment by aldwyn-acn** [comment]
Hi @nreddipalle. This is noted. I'll check on it tomorrow.

**Comment by siosphere** [comment]
I also am not seeing a deploy title when supplying one

**Comment by aldwyn-acn** [comment]
@nreddipalle Apologies for the late response. `deploy-title` has been removed in the [latest release](https://github.com/toko-bifrost/ms-teams-deploy-card/releases/tag/3.0.0) as it has been deemed unused. Kindly check the latest release notes.
